import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";import{getDatabase,ref,push,set,onValue,update,remove}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js";
/* ضع إعدادات Firebase هنا */
 // Your web app's Firebase configuration
  const firebaseConfig = {
    apiKey: "AIzaSyCkI-iOa7Ou-cluhMP7ueYFhEAV30tmjHc",
    authDomain: "shjartna.firebaseapp.com",
    projectId: "shjartna",
   databaseURL: "https://shjartna-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: "shjartna.firebasestorage.app",
    messagingSenderId: "1063038121519",
    appId: "1:1063038121519:web:fe860504532e548ae278da"
  };
const familyId=new URLSearchParams(location.search).get("family")||"main";let db=null,people={},selected=null,mode="add",pending=null,scale=1,title="شجرتنا العائلية";const $=id=>document.getElementById(id),R={root:"الشخص الأول",father:"الأب",mother:"الأم",brother:"الأخ",sister:"الأخت",son:"الابن",daughter:"الابنة",spouse:"الزوج/الزوجة"};try{if(!firebaseConfig.apiKey.startsWith("PASTE_"))db=getDatabase(initializeApp(firebaseConfig))}catch(e){console.error(e)}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function fill(id,current,exclude){const e=$(id);e.innerHTML='<option value="">غير محدد</option>';Object.entries(people).forEach(([k,p])=>{if(k!==exclude)e.insertAdjacentHTML("beforeend",`<option value="${k}">${esc(p.name)}</option>`)});e.value=current||""}
function openAdd(rel="root",parent=null){mode="add";pending={rel,parent};$("mt").textContent=rel==="root"?"إضافة أول شخص":"إضافة "+R[rel];$("mh").textContent=parent?`سيتم ربط الشخص الجديد بعلاقة ${R[rel]} مع ${people[parent]?.name||""}.`:"أدخل بيانات الشخص.";$("addFields").classList.remove("hidden");$("editFields").classList.add("hidden");$("rel").value=rel;$("gender").value=["mother","sister","daughter"].includes(rel)?"female":"male";$("name").value="";$("birth").value="";$("modal").classList.remove("hidden");$("name").focus()}
function openEdit(id){const p=people[id];if(!p)return;mode="edit";pending={id};$("mt").textContent="تعديل وإدارة العلاقات";$("mh").textContent="غيّر الوالدين والزوج/الزوجة مباشرة."; $("addFields").classList.add("hidden");$("editFields").classList.remove("hidden");$("name").value=p.name||"";$("birth").value=p.birth||"";$("gender").value=p.gender||"male";fill("fatherId",p.fatherId,id);fill("motherId",p.motherId,id);fill("spouseId",p.spouseId,id);$("modal").classList.remove("hidden")}
function close(){$("modal").classList.add("hidden")}
async function save(){const name=$("name").value.trim();if(!name)return $("name").focus();if(mode==="edit"){const id=pending.id,p=people[id],father=$("fatherId").value||null,mother=$("motherId").value||null,spouse=$("spouseId").value||null,patch={name,gender:$("gender").value,birth:$("birth").value.trim(),fatherId:father,motherId:mother,spouseId:spouse};if(db)await update(ref(db,`families/${familyId}/people/${id}`),patch);else{people[id]={...p,...patch};if(spouse&&people[spouse])people[spouse].spouseId=id;render()}if(db&&spouse)await update(ref(db,`families/${familyId}/people/${spouse}`),{spouseId:id});close();return}
const rel=$("rel").value,p={name,gender:$("gender").value,birth:$("birth").value.trim(),fatherId:null,motherId:null,spouseId:null,relation:rel,createdAt:Date.now()},parent=pending.parent;if(parent){const q=people[parent];if(rel==="father")p.fatherId=parent;if(rel==="mother")p.motherId=parent;if(["son","daughter"].includes(rel))(q.gender==="female"?p.motherId=pending.parent:p.fatherId=pending.parent);if(["brother","sister"].includes(rel)){p.fatherId=q.fatherId||null;p.motherId=q.motherId||null}if(rel==="spouse")p.spouseId=parent}if(db){const r=push(ref(db,`families/${familyId}/people`));await set(r,p);if(rel==="spouse")await update(ref(db,`families/${familyId}/people/${parent}`),{spouseId:r.key})}else{const id="p"+Date.now();people[id]=p;if(rel==="spouse")people[parent].spouseId=id}close();render()}
async function del(){if(!selected)return;const p=people[selected],kids=Object.entries(people).filter(([id,x])=>x.fatherId===selected||x.motherId===selected);if(!confirm(`هل تريد حذف «${p.name}»؟\nسيتم حذف الشخص فقط وإزالة روابطه من الأبناء والزوج/الزوجة.`))return;const ops={};kids.forEach(([id,x])=>{if(x.fatherId===selected)ops[`families/${familyId}/people/${id}/fatherId`]=null;if(x.motherId===selected)ops[`families/${familyId}/people/${id}/motherId`]=null});if(p.spouseId)ops[`families/${familyId}/people/${p.spouseId}/spouseId`]=null;if(db){if(Object.keys(ops).length)await update(ref(db),ops);await remove(ref(db,`families/${familyId}/people/${selected}`))}else{kids.forEach(([id,x])=>{if(x.fatherId===selected)x.fatherId=null;if(x.motherId===selected)x.motherId=null});if(p.spouseId&&people[p.spouseId])people[p.spouseId].spouseId=null;delete people[selected];render()}selected=null;$("personActions").classList.add("hidden");$("selected").textContent="اختر شخصًا من الشجرة"}
function layout(){const ids=Object.keys(people),child=new Map(ids.map(id=>[id,[]])),roots=[];ids.forEach(id=>{const p=people[id],par=p.fatherId||p.motherId;if(par&&child.has(par))child.get(par).push(id);else roots.push(id)});const levels=[],edges=[],seen=new Set();function walk(id,d){if(seen.has(id))return;seen.add(id);(levels[d]??=[]).push(id);(child.get(id)||[]).forEach(k=>{edges.push([id,k]);walk(k,d+1)})}roots.forEach(r=>walk(r,0));ids.filter(id=>!seen.has(id)).forEach(id=>walk(id,0));return{levels,edges}}
function render(){const ids=Object.keys(people);$("count").textContent=ids.length;if(!ids.length){$("gens").textContent=0;$("tree").innerHTML='<div class="empty"><div>🌳</div><h2>ابدأوا شجرتكم</h2><p>أضف أول شخص لبناء الشجرة.</p><button class="primary" id="start">＋ إضافة أول شخص</button></div>';$("start").onclick=()=>openAdd();return}const L=layout();$("gens").textContent=L.levels.length;const W=Math.max(1200,...L.levels.map(a=>a.length*174+(a.length-1)*54))+180,H=Math.max(700,L.levels.length*217),pos={};let cards="";L.levels.forEach((a,d)=>{const total=a.length*174+(a.length-1)*54,start=(W-total)/2;a.forEach((id,i)=>{const x=start+i*228,y=60+d*217;pos[id]={x,y};const p=people[id];cards+=`<div class="person ${selected===id?"sel":""}" data-id="${id}" style="left:${x}px;top:${y}px"><button class="plus" data-parent="${id}">＋</button><div class="avatar">${p.gender==="female"?"👩":"👨"}</div><div class="name">${esc(p.name)}</div><div class="meta">${p.birth?esc(p.birth)+" • ":""}${R[p.relation]||"قريب"}</div></div>`})});let lines=`<svg class="links" width="${W}" height="${H}">`;L.edges.forEach(([a,b])=>{const A=pos[a],B=pos[b],x1=A.x+87,y1=A.y+92,x2=B.x+87,y2=B.y,mid=(y1+y2)/2;lines+=`<path d="M${x1} ${y1} V${mid} H${x2} V${y2}"/>`});Object.entries(people).forEach(([id,p])=>{if(p.spouseId&&pos[id]&&pos[p.spouseId]&&id<p.spouseId){const A=pos[id],B=pos[p.spouseId];lines+=`<path class="marriage" d="M${A.x+174} ${A.y+46} H${B.x}"/>`}});lines+="</svg>";$("tree").innerHTML=`<div class="canvas" id="canvas" style="width:${W}px;height:${H}px">${lines}${cards}</div>`;apply();document.querySelectorAll(".person").forEach(n=>n.onclick=e=>{if(e.target.classList.contains("plus"))return;selected=n.dataset.id;$("selected").textContent="المحدد: "+people[selected].name;$("personActions").classList.remove("hidden");render()});document.querySelectorAll(".plus").forEach(b=>b.onclick=e=>{e.stopPropagation();openAdd("brother",b.dataset.parent)})}
function apply(){const c=$("canvas");if(c)c.style.transform=`scale(${scale})`;$("zoom").textContent=Math.round(scale*100)+"%"}
$("addRoot").onclick=()=>openAdd();$("close").onclick=close;$("save").onclick=save;$("edit").onclick=()=>openEdit(selected);$("delete").onclick=del;$("in").onclick=()=>{scale=Math.min(1.4,scale+.1);apply()};$("out").onclick=()=>{scale=Math.max(.6,scale-.1);apply()};$("fit").onclick=()=>{scale=1;apply()};document.querySelectorAll("[data-rel]").forEach(b=>b.onclick=()=>selected?openAdd(b.dataset.rel,selected):alert("حدد شخصًا من الشجرة أولًا."));$("share").onclick=async()=>{try{await navigator.clipboard.writeText(location.href);alert("تم نسخ الرابط.")}catch(e){prompt("انسخ الرابط:",location.href)}};$("settings").onclick=()=>{$("settingsModal").classList.remove("hidden");$("newTitle").value=title};$("closeSettings").onclick=()=>$("settingsModal").classList.add("hidden");$("saveTitle").onclick=async()=>{title=$("newTitle").value.trim()||"شجرتنا العائلية";$("title").textContent=title;if(db)await update(ref(db,`families/${familyId}`),{title});$("settingsModal").classList.add("hidden")};
if(db)onValue(ref(db,`families/${familyId}`),s=>{const d=s.val()||{};people=d.people||{};title=d.title||"شجرتنا العائلية";$("title").textContent=title;render()});else render();